# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app: [client, server]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"
          cache-dependency-path: ${{ matrix.app }}/package-lock.json

      - name: Install dependencies
        working-directory: ${{ matrix.app }}
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Security audit (npm audit)
        working-directory: ${{ matrix.app }}
        run: npm audit --audit-level=high --omit=dev

      - name: Lint (client)
        if: matrix.app == 'client'
        working-directory: ${{ matrix.app }}
        run: npm run lint --if-present

      - name: Build (client)
        if: matrix.app == 'client'
        working-directory: ${{ matrix.app }}
        run: npm run build --if-present

      - name: Test (server)
        if: matrix.app == 'server'
        working-directory: ${{ matrix.app }}
        run: npm test
